function value(key: string) {
  return process.env[key]
}

function truthy(key: string) {
  const val = value(key)?.toLowerCase()
  return val === "true" || val === "1"
}

export namespace Flag {
  export const CODE_HARMONY_AUTO_SHARE = truthy("CODE_HARMONY_AUTO_SHARE")
  export const CODE_HARMONY_GIT_BASH_PATH = value("CODE_HARMONY_GIT_BASH_PATH")
  export const CODE_HARMONY_CONFIG = value("CODE_HARMONY_CONFIG")
  export declare const CODE_HARMONY_CONFIG_DIR: string | undefined
  export const CODE_HARMONY_CONFIG_CONTENT = value("CODE_HARMONY_CONFIG_CONTENT")
  export const CODE_HARMONY_DISABLE_AUTOUPDATE = truthy("CODE_HARMONY_DISABLE_AUTOUPDATE")
  export const CODE_HARMONY_DISABLE_PRUNE = truthy("CODE_HARMONY_DISABLE_PRUNE")
  export const CODE_HARMONY_DISABLE_TERMINAL_TITLE = truthy("CODE_HARMONY_DISABLE_TERMINAL_TITLE")
  export const CODE_HARMONY_PERMISSION = value("CODE_HARMONY_PERMISSION")
  export const CODE_HARMONY_DISABLE_DEFAULT_PLUGINS = truthy("CODE_HARMONY_DISABLE_DEFAULT_PLUGINS")
  export const CODE_HARMONY_DISABLE_LSP_DOWNLOAD = truthy("CODE_HARMONY_DISABLE_LSP_DOWNLOAD")
  export const CODE_HARMONY_ENABLE_EXPERIMENTAL_MODELS = truthy("CODE_HARMONY_ENABLE_EXPERIMENTAL_MODELS")
  export const CODE_HARMONY_DISABLE_AUTOCOMPACT = truthy("CODE_HARMONY_DISABLE_AUTOCOMPACT")
  export const CODE_HARMONY_DISABLE_MODELS_FETCH = truthy("CODE_HARMONY_DISABLE_MODELS_FETCH")
  export const CODE_HARMONY_DISABLE_CLAUDE_CODE = truthy("CODE_HARMONY_DISABLE_CLAUDE_CODE")
  export const CODE_HARMONY_DISABLE_CLAUDE_CODE_PROMPT =
    CODE_HARMONY_DISABLE_CLAUDE_CODE || truthy("CODE_HARMONY_DISABLE_CLAUDE_CODE_PROMPT")
  export const CODE_HARMONY_DISABLE_CLAUDE_CODE_SKILLS =
    CODE_HARMONY_DISABLE_CLAUDE_CODE || truthy("CODE_HARMONY_DISABLE_CLAUDE_CODE_SKILLS")
  export declare const CODE_HARMONY_DISABLE_PROJECT_CONFIG: boolean
  export const CODE_HARMONY_FAKE_VCS = value("CODE_HARMONY_FAKE_VCS")
  export const CODE_HARMONY_CLIENT = value("CODE_HARMONY_CLIENT") ?? "cli"
  export const CODE_HARMONY_SERVER_PASSWORD = value("CODE_HARMONY_SERVER_PASSWORD")
  export const CODE_HARMONY_SERVER_USERNAME = value("CODE_HARMONY_SERVER_USERNAME")

  // Experimental
  export const CODE_HARMONY_EXPERIMENTAL = truthy("CODE_HARMONY_EXPERIMENTAL")
  export const CODE_HARMONY_EXPERIMENTAL_FILEWATCHER = truthy("CODE_HARMONY_EXPERIMENTAL_FILEWATCHER")
  export const CODE_HARMONY_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("CODE_HARMONY_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const CODE_HARMONY_EXPERIMENTAL_ICON_DISCOVERY =
    CODE_HARMONY_EXPERIMENTAL || truthy("CODE_HARMONY_EXPERIMENTAL_ICON_DISCOVERY")
  export const CODE_HARMONY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy(
    "CODE_HARMONY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT",
  )
  export const CODE_HARMONY_ENABLE_EXA =
    truthy("CODE_HARMONY_ENABLE_EXA") || CODE_HARMONY_EXPERIMENTAL || truthy("CODE_HARMONY_EXPERIMENTAL_EXA")
  export const CODE_HARMONY_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number(
    "CODE_HARMONY_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS",
  )
  export const CODE_HARMONY_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("CODE_HARMONY_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const CODE_HARMONY_EXPERIMENTAL_OXFMT = CODE_HARMONY_EXPERIMENTAL || truthy("CODE_HARMONY_EXPERIMENTAL_OXFMT")
  export const CODE_HARMONY_EXPERIMENTAL_LSP_TY = truthy("CODE_HARMONY_EXPERIMENTAL_LSP_TY")
  export const CODE_HARMONY_EXPERIMENTAL_LSP_TOOL =
    CODE_HARMONY_EXPERIMENTAL || truthy("CODE_HARMONY_EXPERIMENTAL_LSP_TOOL")
  export const CODE_HARMONY_DISABLE_FILETIME_CHECK = truthy("CODE_HARMONY_DISABLE_FILETIME_CHECK")
  export const CODE_HARMONY_EXPERIMENTAL_PLAN_MODE =
    CODE_HARMONY_EXPERIMENTAL || truthy("CODE_HARMONY_EXPERIMENTAL_PLAN_MODE")
  export const CODE_HARMONY_EXPERIMENTAL_MARKDOWN = truthy("CODE_HARMONY_EXPERIMENTAL_MARKDOWN")
  export const CODE_HARMONY_MODELS_URL = value("CODE_HARMONY_MODELS_URL")

  function number(key: string) {
    const val = value(key)
    if (!val) return undefined
    const parsed = Number(val)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for CODE_HARMONY_DISABLE_PROJECT_CONFIG
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "CODE_HARMONY_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("CODE_HARMONY_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for CODE_HARMONY_CONFIG_DIR
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "CODE_HARMONY_CONFIG_DIR", {
  get() {
    return value("CODE_HARMONY_CONFIG_DIR")
  },
  enumerable: true,
  configurable: false,
})
