function value(key: string) {
  return process.env[key]
}

function truthy(key: string) {
  const val = value(key)?.toLowerCase()
  return val === "true" || val === "1"
}

export namespace Flag {
  export const EMBERHARMONY_AUTO_SHARE = truthy("EMBERHARMONY_AUTO_SHARE")
  export const EMBERHARMONY_GIT_BASH_PATH = value("EMBERHARMONY_GIT_BASH_PATH")
  export const EMBERHARMONY_CONFIG = value("EMBERHARMONY_CONFIG")
  export declare const EMBERHARMONY_CONFIG_DIR: string | undefined
  export const EMBERHARMONY_CONFIG_CONTENT = value("EMBERHARMONY_CONFIG_CONTENT")
  export const EMBERHARMONY_DISABLE_AUTOUPDATE = truthy("EMBERHARMONY_DISABLE_AUTOUPDATE")
  export const EMBERHARMONY_DISABLE_PRUNE = truthy("EMBERHARMONY_DISABLE_PRUNE")
  export const EMBERHARMONY_DISABLE_TERMINAL_TITLE = truthy("EMBERHARMONY_DISABLE_TERMINAL_TITLE")
  export const EMBERHARMONY_PERMISSION = value("EMBERHARMONY_PERMISSION")
  export const EMBERHARMONY_DISABLE_DEFAULT_PLUGINS = truthy("EMBERHARMONY_DISABLE_DEFAULT_PLUGINS")
  export const EMBERHARMONY_DISABLE_LSP_DOWNLOAD = truthy("EMBERHARMONY_DISABLE_LSP_DOWNLOAD")
  export const EMBERHARMONY_ENABLE_EXPERIMENTAL_MODELS = truthy("EMBERHARMONY_ENABLE_EXPERIMENTAL_MODELS")
  export const EMBERHARMONY_DISABLE_AUTOCOMPACT = truthy("EMBERHARMONY_DISABLE_AUTOCOMPACT")
  export const EMBERHARMONY_DISABLE_MODELS_FETCH = truthy("EMBERHARMONY_DISABLE_MODELS_FETCH")
  export const EMBERHARMONY_DISABLE_CLAUDE_CODE = truthy("EMBERHARMONY_DISABLE_CLAUDE_CODE")
  export const EMBERHARMONY_DISABLE_CLAUDE_CODE_PROMPT =
    EMBERHARMONY_DISABLE_CLAUDE_CODE || truthy("EMBERHARMONY_DISABLE_CLAUDE_CODE_PROMPT")
  export const EMBERHARMONY_DISABLE_CLAUDE_CODE_SKILLS =
    EMBERHARMONY_DISABLE_CLAUDE_CODE || truthy("EMBERHARMONY_DISABLE_CLAUDE_CODE_SKILLS")
  export declare const EMBERHARMONY_DISABLE_PROJECT_CONFIG: boolean
  export const EMBERHARMONY_FAKE_VCS = value("EMBERHARMONY_FAKE_VCS")
  export const EMBERHARMONY_CLIENT = value("EMBERHARMONY_CLIENT") ?? "cli"
  export const EMBERHARMONY_SERVER_PASSWORD = value("EMBERHARMONY_SERVER_PASSWORD")
  export const EMBERHARMONY_SERVER_USERNAME = value("EMBERHARMONY_SERVER_USERNAME")

  // Experimental
  export const EMBERHARMONY_EXPERIMENTAL = truthy("EMBERHARMONY_EXPERIMENTAL")
  export const EMBERHARMONY_EXPERIMENTAL_FILEWATCHER = truthy("EMBERHARMONY_EXPERIMENTAL_FILEWATCHER")
  export const EMBERHARMONY_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("EMBERHARMONY_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const EMBERHARMONY_EXPERIMENTAL_ICON_DISCOVERY =
    EMBERHARMONY_EXPERIMENTAL || truthy("EMBERHARMONY_EXPERIMENTAL_ICON_DISCOVERY")
  export const EMBERHARMONY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy(
    "EMBERHARMONY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT",
  )
  export const EMBERHARMONY_ENABLE_EXA =
    truthy("EMBERHARMONY_ENABLE_EXA") || EMBERHARMONY_EXPERIMENTAL || truthy("EMBERHARMONY_EXPERIMENTAL_EXA")
  export const EMBERHARMONY_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number(
    "EMBERHARMONY_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS",
  )
  export const EMBERHARMONY_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("EMBERHARMONY_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const EMBERHARMONY_EXPERIMENTAL_OXFMT = EMBERHARMONY_EXPERIMENTAL || truthy("EMBERHARMONY_EXPERIMENTAL_OXFMT")
  export const EMBERHARMONY_EXPERIMENTAL_LSP_TY = truthy("EMBERHARMONY_EXPERIMENTAL_LSP_TY")
  export const EMBERHARMONY_EXPERIMENTAL_LSP_TOOL =
    EMBERHARMONY_EXPERIMENTAL || truthy("EMBERHARMONY_EXPERIMENTAL_LSP_TOOL")
  export const EMBERHARMONY_DISABLE_FILETIME_CHECK = truthy("EMBERHARMONY_DISABLE_FILETIME_CHECK")
  export const EMBERHARMONY_EXPERIMENTAL_PLAN_MODE =
    EMBERHARMONY_EXPERIMENTAL || truthy("EMBERHARMONY_EXPERIMENTAL_PLAN_MODE")
  export const EMBERHARMONY_EXPERIMENTAL_MARKDOWN = truthy("EMBERHARMONY_EXPERIMENTAL_MARKDOWN")
  export const EMBERHARMONY_MODELS_URL = value("EMBERHARMONY_MODELS_URL")

  function number(key: string) {
    const val = value(key)
    if (!val) return undefined
    const parsed = Number(val)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for EMBERHARMONY_DISABLE_PROJECT_CONFIG
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "EMBERHARMONY_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("EMBERHARMONY_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for EMBERHARMONY_CONFIG_DIR
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "EMBERHARMONY_CONFIG_DIR", {
  get() {
    return value("EMBERHARMONY_CONFIG_DIR")
  },
  enumerable: true,
  configurable: false,
})
