import { describe, expect, test } from "bun:test"

const source = () => Bun.file(new URL("./voice.tsx", import.meta.url)).text()
const repo = new URL("../../../../", import.meta.url)
const root = (path: string) => Bun.file(new URL(path, repo)).text()

function between(text: string, start: string, end: string): string {
  const from = text.indexOf(start)
  const to = text.indexOf(end, from)
  expect(from).toBeGreaterThanOrEqual(0)
  expect(to).toBeGreaterThan(from)
  return text.slice(from, to)
}

describe("desktop voice context boundary", () => {
  test("desktop provider returns the Tauri voice client before constructing a LiveKit room", async () => {
    const text = await source()
    const desktop = text.indexOf("if (isDesktop())")
    const room = text.indexOf("new Room(")

    expect(desktop).toBeGreaterThanOrEqual(0)
    expect(room).toBeGreaterThanOrEqual(0)
    expect(desktop).toBeLessThan(room)
  })

  test("desktop voice start does not pass a LiveKit grant back to SolidJS", async () => {
    const text = await source()

    expect(text).not.toContain("result.grant")
    expect(text).not.toContain("return result.grant")
  })

  test("desktop voice client never uses the LiveKit browser room or server voice status", async () => {
    const text = await source()
    const desktop = between(text, "function createDesktopVoice()", "function createWebVoice")

    expect(desktop).toContain("startVoice(")
    expect(desktop).toContain("stopVoice()")
    expect(desktop).toContain("interruptVoice()")
    expect(desktop).toContain("beginVoiceTypedInput()")
    expect(desktop).toContain("setVoiceMicEnabled(enabled)")
    expect(desktop).not.toContain("new Room(")
    expect(desktop).not.toContain("RoomAudioRenderer")
    expect(desktop).not.toContain("sdk.client.voice.status")
    expect(desktop).not.toContain("sdk.client.voice.token")
    expect(desktop).not.toContain("room.connect(")
    expect(desktop).not.toContain("localParticipant")
  })

  test("desktop connect lets the native kernel reject unready providers", async () => {
    const text = await source()
    const connect = between(text, "async function connect(sessionID: string", "async function disconnect()")

    expect(connect).toContain("const current = await refresh()")
    expect(connect).toContain("const plan = current?.plan")
    expect(connect).toContain("const result = await startVoice(")
    expect(connect).toContain("await refresh().catch(() => undefined)")
    expect(connect).not.toContain("if (!plan?.ready)")
    expect(connect).not.toContain("Voice is not ready")
    expect(connect).not.toContain("mark(true, true, plan.provider)")
  })

  test("desktop connect does not synthesize connected state after start succeeds", async () => {
    const text = await source()
    const connect = between(text, "async function connect(sessionID: string", "async function disconnect()")
    const start = connect.slice(connect.indexOf("const result = await startVoice("))

    expect(start).toContain("await refresh().catch(() => undefined)")
    expect(start).not.toContain('setState("connected")')
    expect(start).not.toContain('setAgent("listening")')
  })

  test("native audio callbacks use bounded rings instead of mutexed vec buffers", async () => {
    const text = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")

    expect(text).toContain("struct PcmRing")
    expect(text).toContain("UnsafeCell<f32>")
    expect(text).not.toContain("Arc<Mutex<VecDeque<f32>>>")
    expect(text).not.toContain("Arc<Mutex<Vec<f32>>>")
    expect(text).not.toContain("try_lock()")
  })

  test("native model event fanout is bounded and non-blocking", async () => {
    const text = await root("packages/desktop/src-tauri/crates/liquid-audio/src/realtime.rs")

    expect(text).toContain("const EVENT_QUEUE_CAP")
    expect(text).toContain("bounded::<VoiceEvent>(EVENT_QUEUE_CAP)")
    expect(text).toContain("try_send_event")
    expect(text).not.toContain("unbounded::<VoiceEvent>")
    expect(text).not.toContain("event_tx.send(")
  })

  test("native LFM2 decoded PCM stays inside Rust for LiveKit transport", async () => {
    const lfm2 = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const event = between(lfm2, "pub enum RuntimeEvent", "/// VAD and capture-loop knobs")

    expect(event).toContain("Audio")
    expect(event).toContain("pcm: Vec<f32>")
    expect(event).toContain("rate: u32")
    expect(lfm2).toContain("RuntimeEvent::Audio")
    expect(lfm2).toContain("consumer_preserves_decoded_pcm_for_native_transports")
    expect(runtime).toContain("RuntimeEvent::Audio { .. } => true")
    expect(runtime).toContain("audio_frame::AudioFrame")
    expect(runtime).toContain("NativeAudioSource")
    expect(runtime).toContain("fn livekit_audio_frames")
    expect(runtime).toContain("source.capture_frame(&frame)")
    expect(runtime).not.toContain("VoiceEvent::AudioClip { wav")
  })

  test("native LFM2 VAD treats speaker playback as reference audio for barge-in", async () => {
    const runtime = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const tauri = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(runtime).toContain("struct PlaybackReference")
    expect(runtime).toContain("playback.set_playing")
    expect(runtime).toContain("playback.set_idle")
    expect(runtime).toContain("const PLAYBACK_ECHO_MULTIPLIER: f32 = 2.5")
    expect(runtime).toContain("reference_audio_active(assistant, playback, speaker)")
    expect(runtime).toContain("reference_vad_threshold(cfg.vad_threshold, assistant, playback, speaker)")
    expect(runtime).toContain("playback.active() || speaker.len() > 0")
    expect(runtime).toContain("playback.rms() * PLAYBACK_ECHO_MULTIPLIER")
    expect(runtime).toContain("playback_reference_extends_echo_gate_after_generation_finishes")
    expect(runtime).toContain("playback_reference_requires_barge_in_above_echo_floor")
    expect(runtime).toContain("queued_speaker_audio_is_reference_audio_before_output_callback_runs")
    expect(tauri).toContain("can_interrupt: true")
  })

  test("native LFM2 delegation prompt is wired in the Rust kernel", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(text).toContain("const LFM2_CONVERSE_SYSTEM_PROMPT")
    expect(text).toContain("DELEGATE: <a clear, self-contained description of the task>")
    expect(text).toContain("Only emit DELEGATE for genuine work")
    expect(text).toContain("engine.with_system_prompt(LFM2_CONVERSE_SYSTEM_PROMPT)")
    expect(text).toContain("settings.lfm2.delegate.enabled")
    expect(text).toContain(".delegate")
    expect(text).toContain(".target")
    expect(text).toContain('eq_ignore_ascii_case("DELEGATE:")')
    expect(text).toContain('line.get(.."DELEGATE:".len())')
    expect(text).not.toContain('let marker = line.find("DELEGATE:")')
  })

  test("desktop voice control is routed through a bounded Tauri kernel queue", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(text).toContain("const VOICE_COMMAND_CAP")
    expect(text).toContain("mpsc::channel(VOICE_COMMAND_CAP)")
    expect(text).toContain("watch::channel(RuntimeSnapshot::default())")
    expect(text).toContain("enum RuntimeCommand")
    expect(text).not.toContain("session: Mutex<Option<VoiceSession>>")
  })

  test("critical desktop voice controls use bounded async delivery instead of full-queue rejection", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const critical = between(text, "async fn request_critical", "impl Default for VoiceRuntime")
    const ordinary = between(text, "async fn request<T>", "async fn request_critical")

    expect(critical).toContain(".send(cmd(reply))")
    expect(critical).toContain(".await")
    expect(critical).toContain('"voice kernel stopped"')
    expect(ordinary).toContain(".try_send(cmd(reply))")
    expect(ordinary).toContain('"voice kernel command queue is full"')
    expect(text).toContain("pub async fn stop(&self) -> Result<(), String>")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::Stop { reply })")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::Interrupt { reply })")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::SetMicEnabled { enabled, reply })")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::BeginTypedInput { reply })")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::ApplySettings { settings, reply })")
    expect(text).toContain("self.request_critical(|reply| RuntimeCommand::InvalidateProvider { provider, reply })")
  })

  test("desktop voice events fan out through a bounded native buffer", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(text).toContain("type UiChannel = Arc<UiEvents>")
    expect(text).toContain("const UI_EVENT_CAP")
    expect(text).toContain("struct UiEvents")
    expect(text).toContain("mpsc::channel(UI_EVENT_CAP)")
    expect(text).toContain("self.tx.try_send(event)")
    expect(text).toContain("impl Drop for UiEvents")
    expect(text).toContain("self.task.abort()")
    expect(text).toContain("UiEvents::new(channel)")
    expect(text).not.toContain("Arc<Mutex<tauri::ipc::Channel<VoiceEvent>>>")
    expect(text).not.toContain(".map(|channel| channel.send(event).is_ok())")
  })

  test("provider thread completion wakes the Tauri kernel snapshot", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(text).toContain("tauri::async_runtime::spawn(kernel_loop(rx, state_tx, commands.clone()))")
    expect(text).toContain("Reap")
    expect(text).toContain("fn wake_kernel(commands: &mpsc::Sender<RuntimeCommand>)")
    expect(text).toContain("let _ = commands.try_send(RuntimeCommand::Reap)")
    expect(text).toContain("RuntimeCommand::Reap =>")
    expect(text).toContain("wake: mpsc::Sender<RuntimeCommand>")
    expect(text).toContain("wake_kernel(&sink_wake)")
    expect(text).toContain("wake_kernel(&wake)")
    expect(text).toContain('threads.spawn("voice-session", move ||')
    expect(text).toContain('threads.spawn("voice-livekit-session", move ||')
  })

  test("provider reaping follows managed thread completion, not cancellation flags", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const cleanup = between(text, "fn cleanup_finished", "fn publish_snapshot")
    const livekit = between(text, "impl LiveKitSession", "impl Drop for LiveKitSession")
    const lfm2 = between(text, "impl Lfm2Session", "impl Drop for Lfm2Session")
    const livekitFinished = between(livekit, "fn is_finished(&self) -> bool", "async fn interrupt")
    const lfm2Finished = between(lfm2, "fn is_finished(&self) -> bool", "fn interrupt")

    expect(text).toContain("finished: Arc<AtomicBool>")
    expect(text).toContain("let thread_finished = finished.clone()")
    expect(text).toContain("thread_finished.store(true, Ordering::SeqCst)")
    expect(cleanup).toContain("VoiceSession::is_finished")
    expect(livekitFinished).toContain("self.finished.load(Ordering::SeqCst)")
    expect(lfm2Finished).toContain("self.finished.load(Ordering::SeqCst)")
    expect(livekitFinished).not.toContain("self.done.load(Ordering::SeqCst)")
    expect(lfm2Finished).not.toContain("self.done.load(Ordering::SeqCst)")
  })

  test("desktop mic state follows the native runtime snapshot", async () => {
    const text = await source()
    const desktop = between(text, "function createDesktopVoice()", "function createWebVoice")

    expect(desktop).toContain("() => native()?.plan")
    expect(desktop).toContain("if (plan.running)")
    expect(desktop).toContain('return native()?.plan.micEnabled ? "unmuted" : "muted"')
    expect(desktop).toContain('state() !== "connected"')
    expect(desktop).toContain('state() !== "connecting"')
    expect(desktop).toContain('agent() !== "thinking"')
    expect(desktop).toContain('agent() !== "speaking"')
    expect(desktop).toContain("clear()")
    expect(desktop).not.toContain("function mark(")
    expect(desktop).not.toContain("setMic(")
    expect(desktop).not.toContain("runningProvider: active, micEnabled")
  })

  test("desktop mic controls refresh native runtime truth after commands", async () => {
    const text = await source()
    const desktop = between(text, "function createDesktopVoice()", "function createWebVoice")
    const mic = between(desktop, "async function setMicEnabled", "async function beginTypedInput")
    const typed = between(desktop, "async function beginTypedInput", "const micState")

    expect(mic).toContain("await setVoiceMicEnabled(enabled)")
    expect(mic).toContain("await refresh().catch(() => undefined)")
    expect(mic).not.toContain("setMic(")
    expect(mic).not.toContain("mark(true")
    expect(typed).toContain("await beginVoiceTypedInput()")
    expect(typed).toContain("await refresh().catch(() => undefined)")
    expect(typed).not.toContain("setMic(")
    expect(typed).not.toContain("mark(true")
  })

  test("desktop voice commands await the Tauri runtime kernel", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/control.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const lfm2 = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const lfm2Session = between(runtime, "struct Lfm2Session", "impl Lfm2Session")
    const livekitSession = between(runtime, "struct LiveKitSession", "enum LiveKitCommand")

    expect(text).toContain("runtime.snapshot().await")
    expect(text).toContain("runtime.start_lfm2(ctx, settings, channel, bridge).await?")
    expect(text).toContain(".start_livekit(ctx.clone(), settings, grant, channel, bridge)")
    expect(text).toContain("runtime.stop().await")
    expect(runtime).toContain("session.stop(threads).await?")
    expect(runtime).toContain("let (live, main) = Lfm2Runtime::prepare(")
    expect(runtime).toContain('threads.spawn("voice-session", move ||')
    expect(runtime).toContain("wake_kernel(&wake)")
    expect(runtime).toContain("async fn stop_lfm2(threads: &ThreadManager, session: Lfm2Session)")
    expect(runtime).toContain('threads.spawn("voice-lfm2-stop"')
    expect(runtime).toContain("stop_lfm2(threads, session).await")
    expect(runtime).toContain("LFM2 stop task dropped before joining")
    expect(runtime).toContain('threads.spawn("voice-livekit-session"')
    expect(runtime).toContain("tauri::async_runtime::block_on(livekit_session_loop(")
    expect(runtime).toContain("async fn stop_livekit(threads: &ThreadManager, session: LiveKitSession)")
    expect(runtime).toContain('threads.spawn("voice-livekit-stop"')
    expect(runtime).toContain("stop_livekit(threads, session).await")
    expect(runtime).toContain("LiveKit stop task dropped before signalling")
    expect(runtime).toContain("threads.wait()")
    expect(lfm2).toContain("pub fn prepare(")
    expect(lfm2).toContain("session: None")
    expect(lfm2Session).not.toContain("task: Option<AsyncTask>")
    expect(livekitSession).not.toContain("task: Option<AsyncTask>")
    expect(runtime).not.toContain("VoiceSession::Livekit(session) => session.stop().await")
    expect(runtime).not.toContain("LiveKit stop task failed")
    expect(text).toContain("runtime.begin_typed_input().await")
    expect(runtime).not.toContain('"voice-session-stop"')
    expect(runtime).not.toContain("tauri::async_runtime::spawn_blocking(move || session.stop())")
    expect(text).not.toContain("runtime.active_provider()")
  })

  test("typed input is a single kernel command that pauses mic and interrupts voice", async () => {
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const lfm2 = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const control = await root("packages/desktop/src-tauri/src/voice/control.rs")
    const lib = await root("packages/desktop/src-tauri/src/lib.rs")
    const bridge = await root("packages/app/src/lib/voice-settings.ts")
    const voice = await source()

    expect(runtime).toContain("pub async fn begin_typed_input(&self)")
    expect(runtime).toContain("RuntimeCommand::BeginTypedInput")
    expect(runtime).toContain("session.set_mic_enabled(false)")
    expect(runtime).toContain("session.interrupt()")
    expect(runtime).toContain("fn emit_ready(&self) -> Result<(), String>")
    expect(runtime).toContain("self.emit_ready()")
    expect(control).toContain("voice_begin_typed_input")
    expect(control).toContain("runtime.begin_typed_input().await")
    expect(lib).toContain("voice::control::voice_begin_typed_input")
    expect(bridge).toContain('invoke<void>("voice_begin_typed_input")')
    expect(voice).toContain("beginTypedInput: () => Promise<void>")
    expect(voice).toContain("await beginVoiceTypedInput()")
    expect(voice).toContain('event.state === "idle"')
    expect(voice).toContain("!running()")
    expect(voice).toContain('"disconnected"')
    expect(voice).toContain('"connected"')
    expect(runtime).toContain("VoiceState::Idle")
    expect(runtime).toContain("VoiceEvent::Level { rms: 0.0 }")
    expect(runtime).toContain("reset_livekit_audio_state_or_done(&channel, &done, mic_enabled.load(Ordering::SeqCst))")
    expect(lfm2).toContain("mic_enabled.clone()")
    expect(lfm2).toContain("emit_ready(&sink, &stop, &mic_enabled)")
    expect(lfm2).toContain("emit_ready(sink, stop, mic_enabled)")
    expect(lfm2).toContain("RuntimeEvent::Level(0.0)")
    expect(lfm2).toContain("VoiceEvent::TurnComplete | VoiceEvent::Interrupted")
    expect(lfm2).toContain("fn ready_state(mic_enabled: &AtomicBool) -> SessionState")
    expect(lfm2).toContain("fn emit_ready")
    expect(lfm2).toContain("terminal_turn_state_follows_mic_enabled")
    expect(lfm2).toContain("ready_transition_clears_output_level")
    expect(lfm2).toContain("mic_enabled.load(Ordering::SeqCst)")
    expect(lfm2).toContain("SessionState::Idle")
  })

  test("native voice delegation does not trust the webview selected agent for build access", async () => {
    const control = await root("packages/desktop/src-tauri/src/voice/control.rs")

    expect(control).toContain('agent: Some("plan".to_string())')
    expect(control).toContain("session_bridge_defaults_voice_delegation_to_plan")
    expect(control).toContain("session_bridge_does_not_trust_webview_model_override")
    expect(control).toContain("desktop kernel must not trust the webview")
    expect(control).toContain("model: parse_model_ref(target)")
    expect(control).not.toContain("agent: ctx.prompt_mode.clone().or_else(|| ctx.agent.clone())")
    expect(control).not.toContain("parse_model_ref(target).or_else")
    expect(control).not.toContain("ctx.model.as_ref().map")
  })

  test("native LFM2 start only touches the session bridge when Tauri settings enable delegation", async () => {
    const control = await root("packages/desktop/src-tauri/src/voice/control.rs")
    const start = between(control, "pub async fn voice_start", "async fn lfm2_bridge_config")
    const branch = between(start, "VoiceProvider::Lfm2 =>", "VoiceProvider::Livekit =>")
    const livekit = between(start, "VoiceProvider::Livekit =>", "VoiceProvider::Off =>")
    const helper = between(control, "async fn lfm2_bridge_config", "fn session_bridge_config")

    expect(branch).toContain("let bridge = lfm2_bridge_config(&settings, &ctx, &server).await?")
    expect(branch).not.toContain("server.status.clone().await")
    expect(livekit).toContain("let bridge = lfm2_bridge_config(&settings, &ctx, &server).await?")
    expect(livekit).toContain(".start_livekit(ctx.clone(), settings, grant, channel, bridge)")
    expect(livekit).not.toContain("server.status.clone().await")
    expect(helper).toContain("settings.lfm2.delegate.enabled")
    expect(helper).toContain(".delegate")
    expect(helper).toContain(".target")
    expect(helper).toContain(".map(str::trim)")
    expect(helper).toContain(".filter(|target| !target.is_empty())")
    expect(helper).toContain("return Ok(None)")
    expect(helper).toContain("server")
    expect(helper).toContain(".status")
    expect(helper).toContain(".await")
    expect(helper.indexOf("return Ok(None)")).toBeLessThan(helper.indexOf(".status"))
    expect(control).not.toContain("pub delegate_target")
  })

  test("desktop start context does not carry the native delegate target from SolidJS", async () => {
    const voice = await source()
    const bridge = await root("packages/app/src/lib/voice-settings.ts")
    const desktop = between(voice, "function createDesktopVoice()", "function createWebVoice")
    const start = between(bridge, "export interface VoiceStartContext", "export type VoiceStartResult")

    expect(start).not.toContain("delegateTarget")
    expect(desktop).not.toContain("const delegateTarget")
    expect(desktop).not.toContain("delegateTarget,")
    expect(desktop).toContain("startVoice(")
    expect(desktop).toContain("directory: sdk.directory")
  })

  test("desktop provider settings reconciliation is owned by the Tauri runtime", async () => {
    const voice = await source()
    const settings = await root("packages/desktop/src-tauri/src/settings.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const refresh = between(voice, "const refreshSettings = () =>", "window.addEventListener")
    const key = between(runtime, "struct SessionSettingsKey", "enum VoiceSession")

    expect(voice).not.toContain("shouldStopRuntimeForProviderChange")
    expect(refresh).toContain("refresh().catch(() => {})")
    expect(refresh).not.toContain("disconnect()")
    expect(refresh).not.toContain("stopVoice()")
    expect(settings).toContain("runtime: State<'_, VoiceRuntime>")
    expect(settings).toContain("runtime.apply_settings(settings.clone()).await?")
    expect(settings.indexOf("runtime.apply_settings(settings.clone()).await?")).toBeLessThan(
      settings.indexOf("store.set(VOICE_KEY, value)"),
    )
    expect(runtime).toContain("pub async fn apply_settings(&self, settings: VoiceSettings)")
    expect(runtime).toContain("RuntimeCommand::ApplySettings")
    expect(runtime).toContain("apply_settings_to_session(&mut session, &threads, settings).await")
    expect(runtime).toContain("!session.matches_settings(&settings)")
    expect(runtime).toContain("SessionSettingsKey::lfm2(&settings)")
    expect(runtime).toContain("SessionSettingsKey::livekit(&settings)")
    expect(key).toContain("provider: VoiceProvider")
    expect(key).toContain("lfm2: Lfm2Settings")
    expect(key).toContain("livekit: Option<LiveKitSettings>")
    expect(key).not.toContain("last_provider")
    expect(runtime).toContain("return stop_session(session, threads).await")
  })

  test("native LiveKit session has a bounded Rust control loop", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const session = between(text, "struct LiveKitSession", "enum LiveKitCommand")

    expect(text).toContain("const LIVEKIT_COMMAND_CAP")
    expect(text).toContain("mpsc::channel(LIVEKIT_COMMAND_CAP)")
    expect(text).toContain("enum LiveKitCommand")
    expect(text).toContain("livekit_session_loop")
    expect(text).toContain('threads.spawn("voice-livekit-session"')
    expect(text).toContain("tauri::async_runtime::block_on(livekit_session_loop(")
    expect(text).toContain('threads.spawn("voice-livekit-stop"')
    expect(text).not.toContain("tauri::async_runtime::spawn(livekit_session_loop")
    expect(session).not.toContain("task: Option<AsyncTask>")
    expect(text).not.toContain("_grant: LiveKitGrant")
  })

  test("native LiveKit session wakes and exits when the kernel done flag is set", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const branch = between(text, "let mut done_poll", "_ = &mut agent_audio_timeout")

    expect(text).toContain("const LIVEKIT_DONE_POLL_MS")
    expect(branch).toContain("tokio::time::interval")
    expect(branch).toContain("set_missed_tick_behavior")
    expect(branch).toContain("done_poll.tick()")
    expect(branch).toContain("if done.load(Ordering::SeqCst)")
    expect(branch).toContain("break")
  })

  test("native LiveKit startup awaits are cancellable by the kernel stop flag", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const loop = between(text, "async fn livekit_session_loop", "fn livekit_room_options")
    const helper = between(text, "async fn livekit_until_done", "fn clear_livekit_audio")

    expect(text).toContain("future::Future")
    expect(helper).toContain("impl Future<Output = Result<T, E>>")
    expect(helper).toContain("tokio::select!")
    expect(helper).toContain("poll.tick()")
    expect(helper).toContain("done.load(Ordering::SeqCst)")
    expect(helper).toContain("return None")
    expect(loop).toContain("livekit_until_done(&done, Room::connect(&grant.url, &grant.token, options))")
    expect(loop).toContain("livekit_until_done(")
    expect(loop).toContain("user.publish_track(")
    expect(loop).toContain("agent.publish_track(")
    expect(loop).toContain("Room::connect(&grant.url, &grant.agent_token, agent_options)")
    expect(loop).not.toContain("Room::connect(&grant.url, &grant.token, options).await")
    expect(loop).not.toContain("Room::connect(&grant.url, &grant.agent_token, agent_options).await")
  })

  test("native LiveKit UI backpressure cancels the provider instead of ignoring event sends", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const sender = between(text, "fn send_livekit(", "fn livekit_fail")
    const loop = between(text, "async fn livekit_session_loop", "fn livekit_room_options")
    const setMic = between(text, "fn livekit_set_mic(", "fn configure_livekit_audio")
    const handler = between(text, "fn handle_livekit_event(", "fn livekit_agent_audio_subscribed")
    const clear = between(text, "fn clear_livekit_audio", "fn reset_livekit_audio_state")
    const reset = between(text, "fn reset_livekit_audio_state_or_done", "fn spawn_livekit_audio_monitor")
    const monitor = between(text, "fn spawn_livekit_audio_monitor(", "fn rms_i16")
    const mic = between(text, "fn spawn_native_livekit_agent_mic(", "async fn send_livekit_interrupt")
    const full = mic.slice(
      mic.indexOf("native LiveKit agent utterance queue is full") - 200,
      mic.indexOf("native LiveKit agent utterance queue is full") + 240,
    )

    expect(sender).toContain("done.store(true, Ordering::SeqCst)")
    expect(loop).toContain("if !send_livekit(")
    expect(loop).toContain("reset_livekit_audio_state_or_done(&channel, &done")
    expect(loop).toContain("livekit_set_mic(&audio, &track, enabled, &channel, &done)")
    expect(setMic).toContain(") -> bool")
    expect(setMic).toContain("send_livekit(")
    expect(handler).toContain("done: &Arc<AtomicBool>")
    expect(handler).toContain("return Some(None)")
    expect(clear).toContain("done: &Arc<AtomicBool>")
    expect(clear).toContain("cancel_livekit_media_tasks(audio_tasks)")
    expect(clear).toContain("threads.reap()")
    expect(clear).toContain("reset_livekit_audio_state_or_done(channel, done, mic_enabled)")
    expect(reset).toContain("done.store(true, Ordering::SeqCst)")
    expect(monitor).toContain("done: Arc<AtomicBool>")
    expect(monitor).toContain("done.store(true, Ordering::SeqCst)")
    expect(monitor).toContain('threads.spawn("voice-livekit-audio-monitor"')
    expect(monitor).toContain("livekit_audio_monitor_loop")
    expect(monitor).toContain("livekit_media_cancelled(&done, &cancel)")
    expect(mic).toContain("send_livekit(")
    expect(mic).toContain('threads.spawn("voice-livekit-agent-mic"')
    expect(mic).toContain("native_livekit_agent_mic_loop")
    expect(mic).toContain("livekit_media_cancelled(&done, &cancel)")
    expect(full).toContain("done.store(true, Ordering::SeqCst)")
    expect(full).toContain("break;")
    expect(full).not.toContain("continue;")
  })

  test("native LiveKit critical controls use bounded async delivery inside the provider", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const session = between(text, "impl LiveKitSession", "impl Drop for LiveKitSession")

    expect(text).toContain("Some(session) => session.interrupt().await")
    expect(text).toContain("match session.set_mic_enabled(false).await")
    expect(text).toContain("Ok(()) => session.interrupt().await")
    expect(session).toContain("async fn interrupt(&self) -> Result<(), String>")
    expect(session).toContain("async fn set_mic_enabled(&self, enabled: bool) -> Result<(), String>")
    expect(session).toContain("async fn send(&self, command: LiveKitCommand) -> Result<(), String>")
    expect(session).toContain("self.send(LiveKitCommand::SetMicEnabled(enabled)).await?")
    expect(session).toContain("self.commands.send(command).await")
    expect(text).toContain('Err("LiveKit command queue closed".into())')
    expect(session).not.toContain("LiveKit command queue is full")
    expect(session).not.toContain("TrySendError::Full")
  })

  test("native LiveKit stop cannot block on a full provider command queue", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const manager = between(text, "async fn stop_livekit", "struct LiveKitSession")
    const session = between(text, "fn stop(self) -> Result<(), String>", "async fn send(&self")

    expect(manager).toContain("let result = session.stop()")
    expect(manager).toContain("tx.send(result)")
    expect(manager).toContain('"LiveKit stop task dropped before signalling"')
    expect(session).toContain("self.done.swap(true, Ordering::SeqCst)")
    expect(session).toContain("self.bridge_cancel.store(true, Ordering::SeqCst)")
    expect(session).toContain("self.commands.try_send(LiveKitCommand::Stop)")
    expect(session).not.toContain("blocking_send(LiveKitCommand::Stop)")
    expect(text).toContain("livekit_stop_does_not_block_when_provider_queue_is_full")
  })

  test("native LiveKit agent output uses the same desktop delegation bridge as local LFM2", async () => {
    const control = await root("packages/desktop/src-tauri/src/voice/control.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const start = between(control, "VoiceProvider::Livekit =>", "VoiceProvider::Off =>")
    const command = between(runtime, "enum RuntimeCommand", "async fn kernel_loop")
    const events = between(runtime, "fn spawn_native_livekit_agent_events(", "fn handle_native_livekit_agent_event")
    const bridge = between(runtime, "impl BridgeState", "fn delegate_task")

    expect(start).toContain("let bridge = lfm2_bridge_config(&settings, &ctx, &server).await?")
    expect(start).toContain(".start_livekit(ctx.clone(), settings, grant, channel, bridge)")
    expect(command).toContain("bridge: Option<SessionBridgeConfig>")
    expect(runtime).toContain("bridge_cancel: Arc<AtomicBool>")
    expect(runtime).toContain("thread_bridge_cancel")
    expect(runtime).toContain("bridge_cancel.store(true, Ordering::SeqCst)")
    expect(events).toContain("bridge: Option<SessionBridgeConfig>")
    expect(events).toContain("bridge_cancel: Arc<AtomicBool>")
    expect(events).toContain("let bridge_threads = threads.clone()")
    expect(events).toContain("wake: mpsc::Sender<RuntimeCommand>")
    expect(events).toContain("BridgeState::new(")
    expect(events).toContain("bridge_threads")
    expect(events).toContain("bridge_cancel")
    expect(events).toContain("wake")
    expect(events).toContain("bridge_state.handle_realtime_text(&text)")
    expect(events).toContain("bridge_state.handle_realtime_audio()")
    expect(events).toContain("bridge_state.handle_realtime_turn_complete()")
    expect(events).toContain("bridge_state.handle_realtime_interrupted()")
    expect(events).toContain("bridge_state.handle_realtime_error()")
    expect(events.indexOf("bridge_state.handle_realtime_turn_complete()")).toBeLessThan(
      events.indexOf("transcript.clear()"),
    )
    expect(bridge).toContain("fn handle_realtime_text(&mut self, text: &str)")
    expect(bridge).toContain("self.transcript.push_str(text)")
    expect(bridge).toContain("fn handle_realtime_turn_complete(&mut self)")
    expect(bridge).toContain("self.finish_turn()")
    expect(bridge).toContain("fn maybe_delegate(&mut self)")
    expect(bridge).toContain("self.reap_delegate()")
    expect(bridge).toContain("self.task.is_some()")
    expect(bridge).toContain("wake: mpsc::Sender<RuntimeCommand>")
    expect(bridge).toContain("let thread_wake = self.wake.clone()")
    expect(bridge).toContain('self.threads.spawn("voice-delegate-turn"')
    expect(bridge).toContain("tauri::async_runtime::block_on(async move")
    expect(bridge).toContain("DelegateDone {")
    expect(bridge).toContain("wake: thread_wake")
    expect(runtime).toContain("wake_kernel(&self.wake)")
    expect(bridge).toContain("self.task = Some(DelegateTask { done })")
    expect(bridge).toContain("fn reap_delegate(&mut self)")
    expect(bridge).toContain("let _ = self.threads.reap()")
    expect(bridge).toContain("impl Drop for BridgeState")
    expect(bridge).toContain("self.cancel.store(true, Ordering::SeqCst)")
    expect(bridge).toContain("cancel.load(Ordering::SeqCst)")
    expect(runtime).toContain("task: Option<DelegateTask>")
    expect(runtime).toContain("struct DelegateTask")
    expect(runtime).toContain("struct DelegateDone")
    expect(runtime).not.toContain("task: Option<AsyncTask>")
    expect(runtime).not.toContain("active: Arc<AtomicBool>")
  })

  test("native voice delegation cancels server handoff when the UI event queue closes", async () => {
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const bridge = between(runtime, "impl BridgeState", "fn delegate_task")
    const helper = between(runtime, "fn send_or_cancel", "fn send_runtime")
    const task = between(bridge, 'self.threads.spawn("voice-delegate-turn"', "fn reap_delegate")

    expect(helper).toContain("cancel.store(true, Ordering::SeqCst)")
    expect(task).toContain("tauri::async_runtime::block_on(async move")
    expect(task).toContain("if !send_or_cancel(")
    expect(task).toContain("return;")
    expect(task).toContain("let delta_cancel = cancel.clone()")
    expect(task).toContain("run_turn(cfg, task, cancel.clone()")
    expect(task).toContain("send_or_cancel(")
    expect(task).toContain("VoiceEvent::Transcript")
    expect(task).toContain("VoiceEvent::Error")
    expect(task).toContain("VoiceState::Listening")
    expect(task).toContain("Err(message)")
    expect(task).toContain("DelegateDone")
    expect(runtime).toContain("impl Drop for DelegateDone")
    expect(runtime).toContain("wake_kernel(&self.wake)")
    expect(task).toContain("self.task = Some(DelegateTask { done })")
    expect(task).not.toContain("let _ = send(")
    expect(task).not.toContain("send(\n                        &delta_channel")
  })

  test("native LiveKit session connects and publishes the desktop microphone in Rust", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const manifest = await root("packages/desktop/src-tauri/Cargo.toml")
    const cargo = await root("packages/desktop/src-tauri/.cargo/config.toml")

    expect(manifest).toContain("livekit")
    expect(manifest).toContain("rustls-tls-webpki-roots")
    expect(cargo).toContain("link-args=-ObjC")
    expect(text).toContain("livekit_until_done(&done, Room::connect(&grant.url, &grant.token, options))")
    expect(text).toContain("PlatformAudio::new()")
    expect(text).toContain("configure_livekit_audio(&audio)")
    expect(text).toContain("AudioProcessingOptions")
    expect(text).toContain("echo_cancellation: true")
    expect(text).toContain("noise_suppression: true")
    expect(text).toContain("auto_gain_control: true")
    expect(text).toContain('LocalAudioTrack::create_audio_track("microphone", audio.rtc_source())')
    expect(text).toContain("user.publish_track(")
    expect(text).toContain("TrackSource::Microphone")
  })

  test("native LiveKit session observes remote audio under the Rust kernel", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")

    expect(text).toContain("const LIVEKIT_AGENT_AUDIO_TIMEOUT_MS")
    expect(text).toContain("let mut remote_audio_seen = false")
    expect(text).toContain("agent_audio_timeout")
    expect(text).toContain("Native LiveKit agent audio track did not subscribe")
    expect(text).not.toContain("LIVEKIT_AGENT_NAME")
    expect(text).toContain("livekit_agent_audio_subscribed(&event, &grant.agent_identity)")
    expect(text).toContain("remote_audio_seen = true")
    expect(text).toContain("match RealtimePipeline::spawn(engine)")
    expect(text).toContain("Native LiveKit agent pipeline failed to start")
    expect(text).toContain("agent_pipe.handle()")
    expect(text).toContain("Room::connect(&grant.url, &grant.agent_token, agent_options)")
    expect(text).toContain("NativeAudioSource::new(")
    expect(text).toContain("let agent_track = LocalAudioTrack::create_audio_track(")
    expect(text).toContain('"assistant"')
    expect(text).toContain("RtcAudioSource::Native(agent_source.clone())")
    expect(text).toContain("spawn_native_livekit_agent_events(")
    expect(text).toContain("handle_native_livekit_agent_event(")
    expect(text).toContain("handle.submit(utt)")
    expect(text).toContain("NativeAudioStream::new(")
    expect(text).toContain("RoomEvent::TrackSubscribed")
    expect(text).toContain("RemoteTrack::Audio(track)")
    expect(text).toContain("&grant.agent_identity")
    expect(text).toContain("agent_identity: &str")
    expect(text).toContain("participant.identity().0 != agent_identity")
    expect(text).toContain("mic_enabled: &Arc<AtomicBool>")
    expect(text).toContain("mic_enabled.clone()")
    expect(text).toContain("clear_livekit_audio(")
    expect(text).toContain("LiveKitMediaTask")
    expect(text).toContain("cancel_livekit_media_tasks")
    expect(text).toContain('threads.spawn("voice-livekit-agent-mic"')
    expect(text).toContain('threads.spawn("voice-livekit-audio-monitor"')
    expect(text).toContain("livekit_media_cancelled(&done, &cancel)")
    expect(text).toContain("let _ = threads.wait()")
    expect(text).toContain("reset_livekit_audio_state_or_done(channel, done, mic_enabled)")
    expect(text).toContain("LIVEKIT_REMOTE_SPEAKING_RMS")
    expect(text).toContain("LIVEKIT_REMOTE_SILENCE_MS")
    expect(text).toContain("last_voice.elapsed() >= silence")
    expect(text).toContain("VoiceState::Speaking")
    expect(text).toContain("VoiceState::Listening")
    expect(text).toContain("VoiceState::Idle")
    expect(text).toContain("rms_i16(frame.data.as_ref())")
    expect(text).toContain("RoomEvent::TrackUnsubscribed")
    expect(text).not.toContain("async fn abort_async_tasks(tasks: &mut Vec<AsyncTask>)")
    expect(text).toContain("VoiceEvent::Level { rms: 0.0 }")
  })

  test("native realtime worker thread startup reports errors instead of panicking", async () => {
    const realtime = await root("packages/desktop/src-tauri/crates/liquid-audio/src/realtime.rs")
    const voice = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const realtimeProd = between(realtime, "impl RealtimePipeline", "// ---------------------------------------------------------------------------------------")
    const voiceProd = between(voice, "fn session_loop", "#[cfg(test)]")
    const livekit = between(runtime, "async fn livekit_session_loop", "fn livekit_room_options")

    expect(realtimeProd).toContain("pub fn spawn<E: VoiceEngine + 'static>(mut engine: E) -> Result<Self, String>")
    expect(realtimeProd).toContain('map_err(|e| format!("spawn lfm2-inference worker failed: {e}"))?')
    expect(voiceProd).toContain("match RealtimePipeline::spawn(engine)")
    expect(voiceProd).toContain('RuntimeEvent::Error(format!("realtime pipeline: {error}"))')
    expect(voiceProd).toContain("match spawn_consumer(")
    expect(voiceProd).toContain('RuntimeEvent::Error(format!("voice consumer: {error}"))')
    expect(voiceProd).toContain('map_err(|e| format!("spawn voice-consumer thread failed: {e}"))')
    expect(voice).toContain("pub fn start(")
    expect(voice).toContain(") -> Result<Self, String>")
    expect(voice).toContain('map_err(|e| format!("spawn voice-session thread failed: {e}"))?')
    expect(livekit).toContain("match RealtimePipeline::spawn(engine)")
    expect(livekit).toContain("Native LiveKit agent pipeline failed to start")
    expect(voice).not.toContain('expect("spawn voice-session thread")')
    expect(realtimeProd).not.toContain('expect("spawn lfm2-inference worker")')
    expect(voiceProd).not.toContain('expect("spawn voice-consumer thread")')
  })

  test("native LiveKit helper threads are owned by the desktop thread manager", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const threads = await root("packages/desktop/src-tauri/src/voice/threads.rs")
    const manager = between(threads, "pub(crate) struct ThreadManager", "impl Drop for ThreadManager")
    const drop = threads.slice(threads.indexOf("impl Drop for ThreadManager"))
    const spawn = between(text, "impl LiveKitSession", "impl Drop for LiveKitSession")
    const events = between(text, "fn spawn_native_livekit_agent_events(", "fn handle_native_livekit_agent_event")
    const agentMic = between(text, "fn spawn_native_livekit_agent_mic(", "async fn send_livekit_interrupt")
    const monitor = between(text, "fn spawn_livekit_audio_monitor(", "fn rms_i16")

    expect(threads).toContain("#[derive(Clone, Default)]")
    expect(manager).toContain("handles: Arc<Mutex<Vec<JoinHandle<()>>>>")
    expect(manager).toContain("let current = std::thread::current().id()")
    expect(manager).toContain("handle.thread().id() == current")
    expect(drop).toContain("let current = std::thread::current().id()")
    expect(drop).toContain("handle.thread().id() == current")
    expect(drop).toContain("handles.extend(live)")
    expect(spawn).toContain("let thread_manager = threads.clone()")
    expect(spawn).toContain("livekit_session_loop(")
    expect(spawn).toContain("thread_manager")
    expect(events).toContain("threads: &ThreadManager")
    expect(events).toContain('threads.spawn("voice-livekit-agent-events"')
    expect(events).not.toContain("ThreadBuilder::new()")
    expect(events).not.toContain('name("voice-livekit-agent-events"')
    expect(text).toContain("struct LiveKitMediaTask")
    expect(text).toContain("fn cancel_livekit_media_tasks")
    expect(agentMic).toContain("threads: &ThreadManager")
    expect(agentMic).toContain('threads.spawn("voice-livekit-agent-mic"')
    expect(agentMic).toContain("tauri::async_runtime::block_on(native_livekit_agent_mic_loop(")
    expect(monitor).toContain("threads: &ThreadManager")
    expect(monitor).toContain('threads.spawn("voice-livekit-audio-monitor"')
    expect(monitor).toContain("tauri::async_runtime::block_on(livekit_audio_monitor_loop(")
    expect(text).toContain("cancel_livekit_media_tasks(&mut agent_audio_tasks)")
    expect(text).toContain("cancel_livekit_media_tasks(&mut audio_tasks)")
    expect(text).toContain("let _ = threads.wait()")
    expect(text).not.toContain("let _ = agent_event_thread.join()")
  })

  test("native LiveKit user-room audio monitor only trusts the native agent identity", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const helper = between(text, "fn livekit_agent_audio_subscribed", "fn clear_livekit_audio")
    const handler = between(text, "fn handle_livekit_event(", "fn livekit_agent_audio_subscribed")

    expect(text).toContain("livekit_agent_audio_subscribed(&event, &grant.agent_identity)")
    expect(helper).toContain("RoomEvent::TrackSubscribed")
    expect(helper).toContain("track: RemoteTrack::Audio(_)")
    expect(helper).toContain("participant.identity().0 == agent_identity")
    expect(handler).toContain("agent_identity: &str")
    expect(handler).toContain("participant.identity().0 != agent_identity")
    expect(handler).toContain("return None")
    expect(handler.indexOf("participant.identity().0 != agent_identity")).toBeLessThan(
      handler.indexOf("spawn_livekit_audio_monitor"),
    )
  })

  test("native LiveKit interrupt uses the in-room control channel and keeps the room loop alive", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const branch = between(text, "LiveKitCommand::Interrupt =>", "LiveKitCommand::SetMicEnabled")

    expect(branch).toContain("agent_handle.interrupt()")
    expect(branch).toContain("agent_source.clear_buffer()")
    expect(branch).toContain("send_livekit_interrupt(&room).await")
    expect(branch).toContain("reset_livekit_audio_state_or_done(")
    expect(branch).toContain("if !reset_livekit_audio_state")
    expect(branch).not.toContain("clear_livekit_audio(&channel, &mut audio_tasks)")
    expect(text).toContain("const LIVEKIT_CONTROL_TOPIC")
    expect(text).toContain("DataPacket")
    expect(text).toContain("publish_data(packet).await")
    expect(text).toContain("fn clear_livekit_audio")
    expect(text).toContain("fn reset_livekit_audio_state")
    expect(text).toContain("VoiceState::Idle")
    expect(text).toContain("let _ = room.close().await;")
  })

  test("native LiveKit agent interruption reaches the in-process LFM2 pipeline", async () => {
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const realtime = await root("packages/desktop/src-tauri/crates/liquid-audio/src/realtime.rs")
    const branch = between(runtime, "LiveKitCommand::Interrupt =>", "LiveKitCommand::SetMicEnabled")

    expect(realtime).toContain("pub struct RealtimePipelineHandle")
    expect(realtime).toContain("pub fn submit(&self, utt: Utterance) -> bool")
    expect(realtime).toContain("pub fn interrupt(&self)")
    expect(branch).toContain("agent_handle.interrupt()")
    expect(runtime).toContain("handle.interrupt()")
    expect(runtime).toContain("handle.submit(utt)")
  })

  test("native LiveKit agent mic ingestion respects the kernel mic state", async () => {
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const mic = between(runtime, "fn spawn_native_livekit_agent_mic(", "async fn send_livekit_interrupt")

    expect(runtime).toContain("handle_native_livekit_agent_event(")
    expect(runtime).toContain("mic_enabled.clone()")
    expect(mic).toContain("mic_enabled: Arc<AtomicBool>")
    expect(mic).toContain("if !mic_enabled.load(Ordering::SeqCst)")
    expect(mic).toContain("samples.clear()")
    expect(mic.indexOf("if !mic_enabled.load(Ordering::SeqCst)")).toBeLessThan(mic.indexOf("handle.submit(utt)"))
  })

  test("native LiveKit agent mic ingestion uses assistant playback as VAD reference", async () => {
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const events = between(runtime, "fn spawn_native_livekit_agent_events(", "struct LiveKitMediaTask")
    const reference = between(runtime, "struct LiveKitPlaybackReference", "fn handle_native_livekit_agent_event")
    const mic = between(runtime, "fn spawn_native_livekit_agent_mic(", "async fn send_livekit_interrupt")
    const interrupt = between(runtime, "LiveKitCommand::Interrupt =>", "LiveKitCommand::SetMicEnabled")

    expect(runtime).toContain("const LIVEKIT_AGENT_ECHO_GATE_MS")
    expect(runtime).toContain("const LIVEKIT_AGENT_ECHO_MULTIPLIER")
    expect(runtime).toContain("let playback = LiveKitPlaybackReference::new()")
    expect(events).toContain("playback.observe(&pcm, LIVEKIT_AGENT_AUDIO_RATE)")
    expect(events).toContain("playback.clear()")
    expect(interrupt).toContain("playback.clear()")
    expect(reference).toContain("until_ms: AtomicU64")
    expect(reference).toContain("rms_bits: AtomicU32")
    expect(reference).toContain("fn reference_vad_threshold(&self, base: f32) -> f32")
    expect(reference).toContain("base.max(rms * LIVEKIT_AGENT_ECHO_MULTIPLIER)")
    expect(mic).toContain("playback: Arc<LiveKitPlaybackReference>")
    expect(mic).toContain("let threshold = playback.reference_vad_threshold(vad_threshold)")
    expect(mic).toContain("} else if playback.active()")
    expect(mic).toContain("samples.clear()")
    expect(mic.indexOf("let threshold = playback.reference_vad_threshold(vad_threshold)")).toBeLessThan(
      mic.indexOf("handle.submit(utt)"),
    )
  })

  test("native audio paths reject zero sample rates before realtime buffering", async () => {
    const resample = await root("packages/desktop/src-tauri/crates/liquid-audio/src/resample.rs")
    const processor = await root("packages/desktop/src-tauri/crates/liquid-audio/src/processor.rs")
    const realtime = await root("packages/desktop/src-tauri/crates/liquid-audio/src/realtime.rs")
    const voice = await root("packages/desktop/src-tauri/crates/liquid-audio/src/voice_runtime.rs")
    const runtime = await root("packages/desktop/src-tauri/src/voice/runtime.rs")
    const mic = between(runtime, "fn spawn_native_livekit_agent_mic(", "async fn send_livekit_interrupt")
    const frames = between(runtime, "fn livekit_audio_frames", "fn livekit_fail")

    expect(resample).toContain("orig_freq == 0 || new_freq == 0")
    expect(resample).toContain("sample rates must be non-zero")
    expect(processor).toContain("if sampling_rate == 0")
    expect(processor).toContain("add_audio: sampling_rate must be non-zero")
    expect(realtime).toContain("utterance sample rate must be non-zero")
    expect(realtime).toContain("Mimi codec sample rate must be non-zero")
    expect(realtime).toContain("output sample rate must be non-zero")
    expect(voice).toContain("audio input sample rate is zero")
    expect(voice).toContain("audio output sample rate is zero")
    expect(mic).toContain("if rate == 0")
    expect(mic).toContain("native LiveKit microphone frame sample rate is zero")
    expect(mic.indexOf("if rate == 0")).toBeLessThan(mic.indexOf("i16_to_f32"))
    expect(frames).toContain("pcm.is_empty() || rate == 0 || channels == 0")
  })

  test("desktop LiveKit token and credential ownership lives in Tauri", async () => {
    const control = await root("packages/desktop/src-tauri/src/voice/control.rs")
    const livekit = await root("packages/desktop/src-tauri/src/voice/livekit.rs")
    const lib = await root("packages/desktop/src-tauri/src/lib.rs")
    const bridge = await root("packages/app/src/lib/voice-settings.ts")
    const settings = await root("packages/app/src/components/settings-voice.tsx")

    expect(control).toContain("livekit::configured(&settings)?")
    expect(control).toContain("settings::lfm2_active_model_dir(&settings.lfm2).is_some()")
    expect(control).toContain("livekit::grant(&settings, &ctx).await?")
    expect(control).toContain("LIVEKIT_READY_DETAIL")
    expect(control).not.toContain("waiting for the external emberharmony-voice agent")
    expect(control).not.toContain("LiveKitTokenRequest")
    expect(control).not.toContain("/voice/token")
    expect(livekit).toContain("AccessToken::with_api_key")
    expect(livekit).toContain("VideoGrants")
    expect(livekit).toContain("let agent_identity = format!")
    expect(livekit).toContain("agent_token")
    expect(livekit).not.toContain("LIVEKIT_AGENT_NAME")
    expect(livekit).not.toContain("RoomConfiguration")
    expect(livekit).not.toContain("RoomAgentDispatch")
    expect(livekit).not.toContain("AgentDispatchClient")
    expect(livekit).not.toContain("RoomClient")
    expect(livekit).not.toContain("ensure_agent_dispatched")
    expect(livekit).not.toContain("CreateAgentDispatchRequest")
    expect(livekit).toContain("voice_livekit_credentials_set")
    expect(livekit).toContain("voice_livekit_credentials_status")
    expect(livekit).toContain("runtime: State<'_, VoiceRuntime>")
    expect(livekit).toContain("runtime.invalidate_provider(VoiceProvider::Livekit).await")
    expect(lib).toContain("voice::livekit::voice_livekit_credentials_set")
    expect(lib).toContain("voice::livekit::voice_livekit_credentials_status")
    expect(bridge).toContain("voice_livekit_credentials_set")
    expect(bridge).toContain("voice_livekit_credentials_status")
    expect(bridge).toContain("window.dispatchEvent(new CustomEvent(VOICE_SETTINGS_CHANGED, { detail: undefined }))")
    expect(settings).toContain("getLiveKitCredentialsStatus")
    expect(settings).toContain("setLiveKitCredentials(key, secret)")
    expect(settings).toContain("const status = await getVoiceStatus()")
  })

  test("native session bridge decodes complete SSE frames before UTF-8 text", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/session.rs")

    expect(text).toContain("buffer: Vec<u8>")
    expect(text).toContain("stream.buffer.extend_from_slice(&chunk)")
    expect(text).toContain("fn sse_boundary(buffer: &[u8]) -> Option<(usize, usize)>")
    expect(text).toContain("std::str::from_utf8(&bytes[..boundary])")
    expect(text).toContain("sse_stream_preserves_utf8_across_network_chunks")
    expect(text).toContain("drain_event_accepts_crlf_sse_boundaries")
    expect(text).not.toContain("String::from_utf8_lossy(&chunk)")
  })

  test("native session bridge bounds delegated SSE and HTTP error bodies", async () => {
    const text = await root("packages/desktop/src-tauri/src/voice/session.rs")

    expect(text).toContain("const SESSION_BRIDGE_CONNECT_TIMEOUT_SECS")
    expect(text).toContain("const SESSION_BRIDGE_READ_TIMEOUT_SECS")
    expect(text).toContain("const SESSION_BRIDGE_ERROR_BODY_CAP")
    expect(text).toContain("const SESSION_BRIDGE_SSE_BUFFER_CAP")
    expect(text).toContain("tokio::time::timeout(")
    expect(text).toContain("session event stream did not connect")
    expect(text).toContain("wait_cancel(cancel)")
    expect(text).toContain("stream.buffer.len().saturating_add(chunk.len())")
    expect(text).toContain("session event frame exceeded")
    expect(text).toContain("async fn capped_error_body")
    expect(text).toContain("fn utf8_prefix")
    expect(text).toContain("error.valid_up_to()")
    expect(text).toContain("utf8_prefix_cuts_at_complete_char_boundary")
    expect(text).toContain("sse_stream_rejects_unbounded_frame_without_boundary")
    expect(text).not.toContain("response.text().await")
  })

  test("desktop sidecar opts out of the legacy voice worker runtime", async () => {
    const lib = await root("packages/desktop/src-tauri/src/lib.rs")
    const worker = await root("packages/emberharmony/src/voice/worker.ts")
    const build = await root("packages/desktop/scripts/build-local.ts")

    expect(lib).toContain('env("EMBERHARMONY_DESKTOP_NATIVE_VOICE", "1")')
    expect(lib).not.toContain("EMBERHARMONY_VOICE_RUNTIME_DIR")
    expect(lib).not.toContain("resources/voice")
    expect(lib).not.toContain("agent.js")
    expect(lib).not.toContain("voice runtime not bundled")
    expect(worker).toContain('process.env["EMBERHARMONY_DESKTOP_NATIVE_VOICE"] === "1"')
    expect(worker).toContain("legacy voice agent worker not started")
    expect(build).toContain("desktop bundle no longer ships a separate LiveKit Node voice runtime")
  })

  test("settings keep the selected native provider separate from voice enablement", async () => {
    const settings = await root("packages/app/src/components/settings-voice.tsx")
    const bridge = await root("packages/app/src/lib/voice-settings.ts")
    const rust = await root("packages/desktop/src-tauri/src/settings.rs")

    expect(bridge).toContain("lastProvider?: Exclude<VoiceProvider")
    expect(bridge).toContain('lastProvider: "lfm2"')
    expect(settings).toContain("const rememberedProvider = ()")
    expect(settings).toContain("if (!enabled())")
    expect(settings).toContain("const settings = { ...base, lastProvider: next }")
    expect(settings).toContain("const settings = { ...base, provider: next, lastProvider }")
    expect(rust).toContain("pub last_provider: Option<VoiceProvider>")
    expect(rust).toContain("fn default_last_provider() -> Option<VoiceProvider>")
    expect(rust).toContain('assert_eq!(json["lastProvider"], "lfm2")')
  })

  test("desktop voice settings save LiveKit configuration only through Tauri", async () => {
    const settings = await root("packages/app/src/components/settings-voice.tsx")
    const config = between(settings, "const [config, { refetch }]", "const [tauriVoice")
    const provider = between(settings, "const provider = (): VoiceProvider =>", "const enabled = ()")
    const toggle = between(settings, "async function toggleVoice", "async function selectProvider")
    const select = between(settings, "async function selectProvider", "async function updateLfm2")
    const update = between(settings, "async function update(patch", "async function saveConnection")
    const save = between(settings, "async function saveConnection", "async function testConnection")

    expect(config).toContain("desktop")
    expect(config).toContain("Promise.resolve(undefined)")
    expect(provider).toContain('if (!desktop && livekitConfigured()) return "livekit"')
    expect(toggle).toContain('if (!desktop && previous === "livekit" && next !== "livekit")')
    expect(toggle).toContain('if (!desktop && next === "livekit")')
    expect(select).toContain('if (!desktop && previous === "livekit" && next !== "livekit")')
    expect(select).toContain('if (!desktop && next === "livekit")')
    expect(update).toContain("if (desktop)")
    expect(update).toContain('await updateLiveKit(patch as Partial<VoiceSettings["livekit"]>)')
    expect(update).toContain("globalSDK.client.voice")
    expect(settings).toContain("const showNativeModel = ()")
    expect(settings).toContain('activeProvider() === "lfm2" || (desktop && activeProvider() === "livekit")')
    expect(settings).toContain("const showLegacyLiveKitModels = () => !desktop")
    expect(settings).toContain("<Show when={showNativeModel()}>")
    expect(settings).toContain("<Show when={showLegacyLiveKitModels()}>")
    expect(save).toContain("await updateLiveKit({ url: nextUrl || undefined })")
    expect(save).toContain("await setLiveKitCredentials(key, secret)")
    expect(save).toContain("if (!desktop)")
    expect(save).toContain("globalSDK.client.auth.set")
    expect(save).toContain("globalSDK.client.voice.configUpdate")
    expect(settings).not.toContain("transitional worker")
    expect(settings).not.toContain("sidecar config")
  })

  test("desktop LFM2 model download persists the native snapshot before reporting success", async () => {
    const settings = await root("packages/app/src/components/settings-voice.tsx")
    const download = between(settings, "async function downloadModel", "const updateDelegate")

    expect(download).toContain("await downloadVoiceModel({ source, revision: lfm2().revision }")
    expect(download).toContain('case "done":')
    expect(download).toContain("setModelDirEdit(event.dir)")
    expect(download).toContain("const saved = await updateLfm2({ modelDir: event.dir })")
    expect(download).toContain("if (!saved) return")
    expect(download).toContain(
      'showToast({ title: language.t("settings.voice.download.done"), description: event.dir })',
    )
    expect(download.indexOf("const saved = await updateLfm2({ modelDir: event.dir })")).toBeLessThan(
      download.indexOf("if (!saved) return"),
    )
    expect(download.indexOf("if (!saved) return")).toBeLessThan(
      download.indexOf('showToast({ title: language.t("settings.voice.download.done"), description: event.dir })'),
    )
  })

  test("desktop LFM2 model downloads are owned by a bounded native runtime", async () => {
    const model = await root("packages/desktop/src-tauri/src/voice/model.rs")
    const lib = await root("packages/desktop/src-tauri/src/lib.rs")
    const module = await root("packages/desktop/src-tauri/src/voice/mod.rs")
    const threads = await root("packages/desktop/src-tauri/src/voice/threads.rs")
    const runtime = between(model, "pub struct ModelDownloadRuntime", "/// Download a model snapshot")
    const command = between(model, "pub async fn voice_model_download", "/// Open a native folder picker")
    const manager = between(threads, "pub(crate) struct ThreadManager", "impl Drop for ThreadManager")

    expect(lib).toContain("app.manage(voice::model::ModelDownloadRuntime::default())")
    expect(module).toContain("mod threads")
    expect(model).toContain("use super::threads::ThreadManager")
    expect(runtime).toContain("threads: ThreadManager")
    expect(runtime).toContain("fn spawn(&self")
    expect(runtime).toContain("self.threads.spawn_if_idle(")
    expect(runtime).toContain("voice model download already running")
    expect(runtime).toContain('"voice-model-download"')
    expect(manager).toContain("pub(crate) fn spawn_if_idle(")
    expect(manager).toContain("self.reap()?")
    expect(manager).toContain("if !handles.is_empty()")
    expect(manager).toContain("ThreadBuilder::new()")
    expect(manager).toContain(".name(name.into())")
    expect(command).toContain("runtime: State<'_, ModelDownloadRuntime>")
    expect(command).toContain("runtime.spawn(move ||")
    expect(model).not.toContain("Mutex<Vec<JoinHandle<()>>>")
    expect(model).not.toContain("thread::{Builder as ThreadBuilder, JoinHandle}")
    expect(model).not.toContain("std::thread::Builder::new()")
  })

  test("prompt input pauses native voice while text input or prompt execution is active", async () => {
    const text = await root("packages/app/src/components/prompt-input.tsx")

    expect(text).toContain("voiceMicTarget(voice.state(), prompt.dirty(), working())")
    expect(text).toContain("voice.beginTypedInput().catch(() => {})")
    expect(text).toContain('if (voice.state() === "connected") await voice.beginTypedInput().catch(() => {})')
    expect(text).toContain("if (voiceMic() === false) voice.setMicEnabled(true).catch(() => {})")
  })

  test("prompt input stop button interrupts voice before aborting prompt work", async () => {
    const text = await root("packages/app/src/components/prompt-input.tsx")
    const abort = between(text, "const abort = async () =>", "const addToHistory")

    expect(abort).toContain("const speaking = voice.turnActive()")
    expect(abort).toContain("await voice.interrupt().catch(() => {})")
    expect(abort.indexOf("await voice.interrupt().catch(() => {})")).toBeLessThan(abort.indexOf("sdk.client.session"))
  })

  test("desktop voice docs describe the implemented Tauri kernel command surface", async () => {
    const stack = await root("desktop-stack.md")
    const frontend = await root("packages/desktop/src-tauri/src/voice/FRONTEND_DESIGN.md")
    const architecture = await root("packages/desktop/src-tauri/src/voice/VOICE_ARCHITECTURE.md")

    expect(stack).toContain("The shared named-thread owner lives in `src/voice/threads.rs`")
    expect(stack).toContain("voice-model-download thread")
    expect(stack).toContain("voice-livekit-agent-events")
    expect(stack).toContain("voice-livekit-agent-mic")
    expect(stack).toContain("voice-livekit-audio-monitor")
    expect(stack).not.toContain("LKRemote")
    expect(frontend).toContain("voice_start(app, runtime, server, ctx, channel)")
    expect(frontend).toContain("voice_interrupt(runtime)")
    expect(frontend).toContain("voice_begin_typed_input(runtime)")
    expect(frontend).toContain("SessionCtx { sessionID, directory, model?, agent?, variant?, promptMode? }")
    expect(frontend).toContain("It does not carry `delegateTarget`")
    expect(frontend).not.toContain("voice_start_live")
    expect(frontend).not.toContain("voice_stop_live")
    expect(frontend).not.toContain("voice_abort_turn")
    expect(frontend).not.toContain("voice_generate_turn")
    expect(frontend).not.toContain("delegateTarget?")
    expect(architecture).toContain("threads.rs                     shared ThreadManager")
    expect(architecture).toContain("model.rs                       HF token, model directory picker, ThreadManager-owned download")
    expect(architecture).not.toContain("runtime.rs                     VoiceRuntime kernel, ThreadManager")
    expect(architecture).toContain("voice_settings_set serializes the settings")
    expect(architecture).toContain("only persists after the kernel")
    expect(architecture).toContain("accepts the update")
    expect(architecture).not.toContain("voice_settings_set persists, then RuntimeCommand::ApplySettings")
  })
})
