name: beta

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  sync:
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref_name == 'dev') ||
      (github.event_name == 'push' &&
        github.ref_name == 'dev' &&
        startsWith(github.event.head_commit.message, 'release: v')) ||
      (github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'contributor'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git Committer
        id: setup-git-committer
        uses: ./.github/actions/setup-git-committer

      - name: Sync beta branch
        env:
          GH_TOKEN: ${{ steps.setup-git-committer.outputs.token }}
        run: bun script/beta.ts
